<?php
declare(strict_types=1);
require_once __DIR__ . '/includes/auth.php';
require_once __DIR__ . '/includes/functions.php';

header('Content-Type: application/json; charset=UTF-8');

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['success' => false, 'message' => 'Метод не поддерживается']);
    exit;
}

$token = $_POST['csrf_token'] ?? null;
if (!verify_csrf_token($token)) {
    http_response_code(400);
    echo json_encode(['success' => false, 'message' => 'Неверный CSRF-токен']);
    exit;
}

// Load current config
$config = load_config();
$ldap = $config['ldap'] ?? [];

// Collect inputs
$host = trim((string)($_POST['host'] ?? ''));
$port = (int)($_POST['port'] ?? 0);
$base_dn = trim((string)($_POST['base_dn'] ?? ''));
$service_dn = trim((string)($_POST['service_dn'] ?? ''));
$service_password = (string)($_POST['service_password'] ?? '');
$start_tls = isset($_POST['start_tls']) && ($_POST['start_tls'] === '1' || $_POST['start_tls'] === 'true' || $_POST['start_tls'] === 'on');
$network_timeout = (int)($_POST['network_timeout'] ?? 10);

if ($host === '' || $port <= 0 || $base_dn === '' || $service_dn === '') {
    http_response_code(400);
    echo json_encode(['success' => false, 'message' => 'Заполните все обязательные поля']);
    exit;
}

// Build new config array, preserve service_password if not provided
$new = $config;
$new['ldap'] = [
    'host' => $host,
    'port' => $port,
    'base_dn' => $base_dn,
    'service_dn' => $service_dn,
    'service_password' => ($service_password !== '' ? $service_password : ($ldap['service_password'] ?? '')),
    'start_tls' => $start_tls,
    'bind_timeout' => (int)($ldap['bind_timeout'] ?? 10),
    'network_timeout' => $network_timeout,
];

// Write back to config file safely
$file = __DIR__ . '/config/ldap.php';
if (!is_writable($file)) {
    // Try to change permissions gently; if still not writable, abort
    @chmod($file, 0640);
}
if (!is_writable($file)) {
    http_response_code(500);
    echo json_encode(['success' => false, 'message' => 'Файл конфигурации недоступен для записи']);
    exit;
}

// Export PHP file content
$export = var_export($new, true);
$php = "<?php\n// Generated by AD Control Panel on " . date('c') . "\nreturn " . $export . ";\n";
$tmp = $file . '.tmp';
if (file_put_contents($tmp, $php, LOCK_EX) === false) {
    http_response_code(500);
    echo json_encode(['success' => false, 'message' => 'Не удалось записать временный файл']);
    exit;
}
if (!@rename($tmp, $file)) {
    @unlink($tmp);
    http_response_code(500);
    echo json_encode(['success' => false, 'message' => 'Не удалось заменить файл конфигурации']);
    exit;
}

// Invalidate cached config
if (function_exists('opcache_invalidate')) { @opcache_invalidate($file, true); }
// Also drop in-process cache by resetting the static variable via a reload hook
if (function_exists('apcu_delete')) { @apcu_delete('adpanel_config_cache'); }

log_action('settings_saved', ['host' => $host, 'base_dn' => $base_dn, 'service_dn' => $service_dn]);

echo json_encode(['success' => true, 'message' => 'Настройки сохранены']);
